version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Build job"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Test job"
      - run: sleep 5
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
      # only run this job if build succeeds
        requires:
            - build
